SOURCE_WEATHER = "weather"
SOURCE_TRAFFIC = "traffic"
SOURCE_INCIDENT = "incident"

VALID_SOURCES = {
    SOURCE_WEATHER,
    SOURCE_TRAFFIC,
    SOURCE_INCIDENT,
}

SEVERITY_LOW = "LOW"
SEVERITY_MEDIUM = "MEDIUM"
SEVERITY_HIGH = "HIGH"
SEVERITY_CRITICAL = "CRITICAL"

SEVERITY_LEVELS = {
    SEVERITY_LOW,
    SEVERITY_MEDIUM,
    SEVERITY_HIGH,
    SEVERITY_CRITICAL,
}

DEFAULT_CORRELATION_WINDOW_MINUTES = 30.0
DEFAULT_CORRELATION_DISTANCE_KM = 2.0